apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    dontrun: nginx
    env: dev
    default: prod
  name: pod1
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

