apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    env: prod
  name: prod_pod1
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

