apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    env: dev
  name: pod2
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

